### ISSUE TITLE
Add the content for "Silly Novels by Silly Lady Novelists" to the books repository

### ISSUE THREAD

**Issue by jjcastro** [citapress/citapress#26]
Add the content for "Silly Novels by Silly Lady Novelists" to the books repository at https://github.com/citapress/books.

The HTML source can be found at https://www.gutenberg.org/files/28289/28289-h/28289-h.htm#page178. This content should be converted to Markdown. You can use [`pandoc`](https://pandoc.org/) for this (or any other converter tool).

This should go in its own folder and it should follow the conventions described in the books repository.

**Comment by Sol1323** [comment]
@jjcastro I will be happy to claim this issue.  :)

**Comment by Sol1323** [comment]
@jjcastro Opened a [PR](https://github.com/citapress/books/pull/11) for this issue. 

Thank you for referencing [pandoc](https://pandoc.org/) tool. I tried other tools but resulted in strange conversion errors. 

Let me know if there are any issues with PR. Looking forward to keeping contributing here.

Thanks!

**Comment by jjcastro** [comment]
Hi @Sol1323!

Thanks so much for contributing :) Sorry for the delay!
