### ISSUE TITLE
Reconsider NC

### ISSUE THREAD

**Issue by davelab6** [citapress/citapress#7]
I was disappointed to see CC-SA-NC - Creative Commons doesn't frame this as a license suitable for free cultural works - https://creativecommons.org/share-your-work/public-domain/freeworks/ describes this in more detail

**Comment by davelab6** [comment]
@jjcastro explained the cover images are the only piece that is CC-SA-NC, so that the graphic designers feel more comfortable to contribute. 

I think since the complete book projects have heterogeneous licensing, that should be made more clear, such that the project could explain the range of licenses that are acceptable for each kind of piece, and the preferred licenses :)

**Comment by davelab6** [comment]
For the CC-SA case, I wonder that trademark could provide sufficient cache for the Cita Press financial viability for printing. 

@xuv also mentioned the "peer production license" by dimity kleimer. This is not a libre license but neither is CC-SA-NC... 😝

**Comment by davelab6** [comment]
@jjcastro also mentioned CC attribution requirements could be used more specifically for this

**Comment by juliacastrov** [comment]
We are now CC-SA!

**Comment by xuv** [comment]
Wow. Amazing!
Congratulation @juliacastrov, this is amazing news!
